spring:
  data:
    elasticsearch:
      cluster-name: jaydi
      cluster-nodes: 127.0.0.1:9300
  datasource:
    url: jdbc:mysql://localhost:3306/bitpic?characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    context-path: /api/bitpic

# 腾讯云短信应用相关
#sms:
#  appid:
#  appkey:
#  templateId:
#    registered:   // 注册
#    phone:
#    password:
#    pay:
#  sign:

file:
  root: /Volumes/H/Java/store/
  authenticate-path: authenticate
  authenticate-file-name: authenticate.png
  avatar-path: avatar
  avatar-file-name: avatar.png
  pic-check-path: check
  download-file-name: 0.zip
  certificate-file-name: certificate.txt

img-server:
  root: /Volumes/H/Java/images/

thum:
  mark-file: /Volumes/H/Java/store/mark.png

# aes算法秘钥
aes:
  key: 1234567890123456
